version: "3.8"

services:
  # Cơ sở dữ liệu Không gian (Spatial)
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: travel_os
    ports:
      - "3308:3306"
    volumes:
      - ./mysql/init-schema.sql:/docker-entrypoint-initdb.d/init-schema.sql
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

  # Redis cho Caching và Realtime Collaboration (Giữ lại để sau này làm tính năng Realtime)
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  mysql_data:
  redis_data:
