server:
  port: 8080

spring:
  application:
    name: core-service
  datasource:
    # Kết nối vào cổng 3307 mà chúng ta đã setup ở file docker-compose
    url: jdbc:mysql://localhost:3307/travel_os_db?useSSL=false&serverTimezone=Asia/Ho_Chi_Minh&allowPublicKeyRetrieval=true
    username: travel_admin
    password: travel_password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    # Không dùng update ddl vì ta đã chạy init-schema.sql bên Docker rồi
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    show-sql: true
